using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using ProjectEuler.Interfaces;

namespace ProjectEuler.Solutions
{
    /// <summary>
    /// Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
    /// By starting with 1 and 2, the first 10 terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
    /// Find the sum of all the even-valued terms in the sequence which do not exceed four million.
    /// </summary>
    public class Problem2 : IIntProblem
    {
        public int Solve()
        {
            int sum = 0;
            int num1 = 1;
            int num2 = 2;

            while (num2 <= 4000000)
            {
                if (num2 % 2 == 0)
                {
                    sum += num2;
                }

                int temp = num1;

                num1 = num2;
                num2 += temp;
            }

            return sum;
        }
    }
}
